<a href="https://colab.research.google.com/github/juandi247/mc-2023-juan-diaz/blob/main/taller_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# INGRESO
A = np.array([[3,2,2],
              [3,1,-3],
              [1,0,-2]], dtype=float)



B=np.array([[1,2,0,4],
            [2,0,-1,-2],
            [1,1,-1,0],
            [0,4,1,0]], dtype=float)


def gaussjordan(A):
      tamano = np.shape(A)
      n = tamano[0]
      identidad = np.identity(n)


      AB = np.concatenate((A,identidad),axis=1)
      AB0 = np.copy(AB)


      tamano = np.shape(AB)
      n = tamano[0]
      m = tamano[1]

      for i in range(0,n-1,1):
          columna = abs(AB[i:,i])
          dondemax = np.argmax(columna)

          if (dondemax !=0):
          
              temporal = np.copy(AB[i,:])
              AB[i,:] = AB[dondemax+i,:]
              AB[dondemax+i,:] = temporal
      AB1 = np.copy(AB)


      for i in range(0,n-1,1):
          pivote = AB[i,i]
          adelante = i+1
          for k in range(adelante,n,1):
              factor = AB[k,i]/pivote
              AB[k,:] = AB[k,:] - AB[i,:]*factor
      AB2 = np.copy(AB)


      ultfila = n-1
      ultcolumna = m-1
      for i in range(ultfila,0-1,-1):
          pivote = AB[i,i]
          atras = i-1 
          for k in range(atras,0-1,-1):
              factor = AB[k,i]/pivote
              AB[k,:] = AB[k,:] - AB[i,:]*factor
        
          AB[i,:] = AB[i,:]/AB[i,i]

      inversa = np.copy(AB[:,n:])
      return inversa



# SALIDA
print(gaussjordan(A))
print("\n")
print(gaussjordan(B))

[[ 1.  -2.   4. ]
 [-1.5  4.  -7.5]
 [ 0.5 -1.   1.5]]


[[ 3.33333333e-01  6.66666667e-01 -6.66666667e-01 -1.38777878e-17]
 [-6.66666667e-02 -1.33333333e-01  3.33333333e-01  2.00000000e-01]
 [ 2.66666667e-01  5.33333333e-01 -1.33333333e+00  2.00000000e-01]
 [ 2.00000000e-01 -1.00000000e-01  0.00000000e+00 -1.00000000e-01]]
